Repository Typeslint/github-AutoResponse, pull requests merged in 2023-08, with the labels that each got.

#19 chore: change repository path
  src/index.ts
Labels: Approved, Patch, Core

#20 feat: allow member to merge pull requests
  src/index.ts
Labels: Approved, Minor, Core

#21 chore: Adjust label for proper case sensitivity
  src/index.ts
Labels: Approved, Core

#25 feat: implement pull request mergeability check
  src/index.ts
Labels: Approved, Minor, Core
