Repository Typeslint/github-AutoResponse, pull requests merged in 2023-10, with the labels that each got.

#28 chore: Adjust reply context
  src/index.ts
Labels: Approved, Core

#29 build(CI): update node and npm version
  .github/workflows/lint.yml
Labels: Approved, Patch

#30 test(linter): extends recommended-type-checked and add linter rules
  .eslintrc.json
Labels: Approved, Patch

#31 fix: Add reply outside core dir
  src/index.ts
Labels: Approved, Core

#32 chore(tsconfig): add pretty to compilerOptions
  tsconfig.json
Labels: Approved, Patch

#36 chore: ignore dist directory
  .gitignore
Labels: Approved
