Repository Typeslint/github-AutoResponse, pull requests merged in 2023-11, with the labels that each got.

#37 build(DOCKERFILE): change run script
  Dockerfile
Labels: Approved

#38 feat(API)!: Replace fetch with Node.js 18 module
  src/index.ts
Labels: Approved, Major, Core

#39 style: change quotes to double quote
  src/index.ts
  src/structures/listener.ts
Labels: Approved, Patch, Core

#40 test(linter): add quotes rules
  .eslintrc.json
Labels: Approved

#42 feat(app): create core class
  src/class/issuesClose.ts
  src/class/issuesComment.ts
  src/class/issuesOpen.ts
  src/class/prsOpen.ts
  src/class/prsReview.ts
  src/class/prsStale.ts
  src/class/prsSynchronize.ts
  src/class/push.ts
  src/class/workflowCheck.ts
  src/index.ts
  src/structures/constant.ts
  src/structures/type.ts
Labels: Approved, Major, Core

#43 test(linter) add no-unnecessary-condition and sort-imports rules
  .eslintrc.json
Labels: Approved
