Repository Typeslint/github-AutoResponse, pull requests merged in 2023-12, with the labels that each got.

#47 fix: add missing parentheses to iife
  src/index.ts
Labels: Approved, Patch, Core

#45 fix: inaccessible pull_request number in workflow_run
  src/class/workflowCheck.ts
  src/index.ts
Labels: Approved, Patch, Core

#48 docs: update contribution guide
  CONTRIBUTING.md
Labels: Approved

#49 fix: cast 'head_sha' as string
  src/class/push.ts
Labels: Approved, Patch

#50 refactor: get content changes instead of additions
  src/class/prsOpen.ts
Labels: Approved

#51 docs(README): Adjust README documentation
  README.md
Labels: Approved

#52 build(CI): update node version and npm version
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: Approved

#53 refactor: using curly bracket on conditional
  src/class/issuesOpen.ts
Labels: Approved

#56 chore: Add Security Policy, Templates, and Issue Standardization
  .github/ISSUE_TEMPLATE/Issues.yml
  .github/PULL_REQUEST_TEMPLATE.md
  SECURITY.md
Labels: Approved

#54 style: remove multi spaces and add newlines between class members
  src/class/issuesClose.ts
  src/class/issuesComment.ts
  src/class/prsReview.ts
  src/class/prsStale.ts
  src/class/prsSynchronize.ts
  src/class/push.ts
  src/structures/type.ts
Labels: Approved

#57 chore(release): 3.0.0 Release
  package-lock.json
  package.json
Labels: Approved, Major
